#! /bin/sh
command touch .env
cat > .env << EOF
HOST= $HOST
PORT= $PORT
NODE_ENV= $NODE_ENV
APP_NAME= $APP_NAME
APP_URL= http://${HOST}:${PORT}
APP_KEY= $APP_KEY
DB_CONNECTION= $DB_CONNECTION
DB_USER= $DB_USER
DB_PASSWORD= $DB_PASSWORD
DB_DATABASE= $DB_DATABASE
DB_CONNECTION_WONDER= $DB_CONNECTION_WONDER
DB_HOST_WONDER= $DB_HOST_WONDER
DB_PORT_WONDER= $DB_PORT_WONDER
DB_USER_WONDER= $DB_USER_WONDER
DB_PASSWORD_WONDER= $DB_PASSWORD_WONDER
DB_DATABASE_WONDER= $DB_DATABASE_WONDER
HASH_DRIVER= $HASH_DRIVER
MAIL_CONNECTION= $MAIL_CONNECTION
SMTP_HOST= $SMTP_HOST
MAIL_USERNAME= $MAIL_USERNAME
MAIL_PASSWORD= $MAIL_PASSWORD
EOF